### ISSUE TITLE
A script to help format profiles properly?

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#124]
I prefer to interactively create profiles with `aa-logprof`. In order to follow your profile rules more easily I created the following little script:

```
sed -i.bak \
's|/usr/bin/bash|/{usr/,}bin/{,ba,da}sh|; s|/usr/bin|/{usr/,}bin|; s|owner /proc/\*/|@{PROC}/@{pid}/|; s|/proc|@{PROC}|; s|/sys/devices|@{sys}/devices|; s|/sys/bus|@{sys}/bus|; s|/sys/class|@{sys}/class|; s|/sys/fs|@{sys}/fs|; s|/run|@{run}|; s|/home/\*/|@{HOME}/|; s|/usr/share|@{system_share_dirs}|; s|@{run}/user/1000|@{run}/user/@{uid}|' /etc/apparmor.d/$1
```
In order to avoid the need to escape the slash and to make the code more readable I used `|` as the delimiter.

My scripting abilities are close to non-existent at best and I'm sure that above code can be improved significantly. I'm also aware that many of your guidelines are not covered, like `@{exec_path} mr,`, the sorting rules  for the file block etc. Nevertheless, I think it saves a lot of time.

Do you have any ideas how to improve and enhance that script? It could motivate other people to contribute to your project. Or perhaps you are using your own one which you are willing to share?

**Comment by roddhjav** [comment]
I planned to write a profile formatted, so all this kind of thing will ultimately be automatic. However, I just don't have the time to work on it currently. As a temporary solution, what you have may be good enough.

In general I don't use `aa-logprof` too much because for complex construction it is not enough. Writing a profile is like writing a software, they are some major architectural decision to take:
- First about the security, you need to understand what a programs does before confining it.
- But also about the division of a profile in multiple part. See the gnome profiles.
