### ISSUE TITLE
"Profile ... not found" when executing makepkg -si

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#160]
When executing makepkg -si I get the following output:

```
‼ Profile akonadi_agent_launcher not found
 ‼ Profile akonadi_agent_server not found
 ‼ Profile akonadi_davgroupware_resource not found
 ‼ Profile akonadi_etesync_resource not found
 ‼ Profile akonadi_ews_resource not found
 ‼ Profile akonadi_ewsmta_resource not found
 ‼ Profile akonadi_google_resource not found
 ‼ Profile akonadi_icaldir_resource not found
 ‼ Profile akonadi_imap_resource not found
 ‼ Profile akonadi_knut_resource not found
 ‼ Profile akonadi_kolab_resource not found
 ‼ Profile akonadi_mbox_resource not found
 ‼ Profile akonadi_mixedmaildir_resource not found
 ‼ Profile akonadi_notes_resource not found
 ‼ Profile akonadi_openxchange_resource not found
 ‼ Profile akonadi_pop3_resource not found
 ‼ Profile akonadi_rds not found
 ‼ Profile akonadi_tomboynotes_resource not found
 ‼ Profile akonadi_vcard_resource not found
 ‼ Profile akonadi_vcarddir_resource not found
 ‼ Profile atril-previewer not found
 ‼ Profile ctop not found
 ‼ Profile evince-previewer not found
 ‼ Profile evince-thumbnailer not found
 ‼ Profile man not found
 ‼ Profile plasma-discover not found
```
Most of these profiles do not exist yet. But two of them, namely for `man` and `plasma-discover` , do exist so I think they should be removed from that list.

**Comment by roddhjav** [comment]
This is just a warning message that I put in order to track the program with [flags defined](https://github.com/roddhjav/apparmor.d/tree/main/dists/flags) but without profiles. This help me to check bug due to flags issues.

When a warning is raised it means either the profile exist but has not yet be pushed to the public repo or the profile has been [explicitly disabled](https://github.com/roddhjav/apparmor.d/tree/main/dists/ignore). In both case, this is because the profile is still in a early dev stage.

**Comment by curiosityseeker** [comment]
Thanks, understood!
