### ISSUE TITLE
aalog -r and -R do not honor the owner qualifier

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#295]
Example:

`aalog` reports:

`ALLOWED pacman//gpg file_inherit owner /dev/tty comm=gpgconf requested_mask=wr denied_mask=wr`

However, `aalog -r` output:

```
profile pacman//gpg {
  /dev/tty rw,  # file_inherit
}
```
And `aalog -R` :

`apparmor="ALLOWED" operation="file_inherit" class="file" profile="pacman//gpg" name="/dev/tty"  comm="gpgconf" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0 FSUID="root" OUID="root"`

So in both cases the `owner` qualifier is missing.

Btw.: What is the correct syntax for adding/modifying rules for a child profile in `local`?

**Comment by roddhjav** [comment]
`aa-log -R` is the raw format from auditd/syslog/journalctl therefore, it is the *source of truth*. `aa-log` & `aa-log -r` use totally different function to show the log, that's why the result may differ. Arguably, for this log both rule should work fine (`root` reading `root` stuff).

For `aa-log -r` I end up printing `owner` only when fsuid == ouid **and** this is not the root user. See: https://github.com/roddhjav/apparmor.d/blob/738f7cc0c2e5d0cd446f1bf3b65f6411b812186e/pkg/aa/rules.go#L44

> Btw.: What is the correct syntax for adding/modifying rules for a child profile in local?

There is no particular syntax, this is your own place for your own rules, you do what you want.

All subprofiles should have a local include name as follow: `local/<profile>_<subprofile>`. Example for `pass_editor`: https://github.com/roddhjav/apparmor.d/blob/738f7cc0c2e5d0cd446f1bf3b65f6411b812186e/apparmor.d/profiles-m-r/pass#L95

Some subprofiles may be missing this include, fell free to open a PR to add them.

**Comment by curiosityseeker** [comment]
> `aa-log -R` is the raw format from auditd/syslog/journalctl therefore, it is the _source of truth_. `aa-log` & `aa-log -r` use totally different function to show the log, that's why the result may differ. Arguably, for this log both rule should work fine (`root` reading `root` stuff).
> 
> For `aa-log -r`, I end up printing `owner` only when `fsuid == ouid` **and** when the user is not `root`. See:
> 
> https://github.com/roddhjav/apparmor.d/blob/738f7cc0c2e5d0cd446f1bf3b65f6411b812186e/pkg/aa/rules.go#L44
> 
> Otherwise, this would result with generated profile full of `owner` in front of `/usr/share/`, `@{lib}`, `@{bin}`, `@{sys}` ... breaking all programs the ability to be run indifferently as user or as root.

Ah, I see. Thanks!

> 
> > Btw.: What is the correct syntax for adding/modifying rules for a child profile in local?
> 
> There is no particular syntax, this is your own place for your own rules, you do what you want.
> 
> All subprofiles should have a local include name as follow: `local/<profile>_<subprofile>`. Example for `pass_editor`:
> 
> https://github.com/roddhjav/apparmor.d/blob/738f7cc0c2e5d0cd446f1bf3b65f6411b812186e/apparmor.d/profiles-m-r/pass#L95

Sorry, I asked the wrong question. For some inexplicable reason I hadn't noticed the `local/<profile>_<subprofile>` includes. Aarrgggh :(
> 
> Some subprofiles may be missing this include, fell free to open a PR to add them.

Sure I'll do!
