### ISSUE TITLE
Firefox profile capabilities 

### ISSUE THREAD

**Issue by cdbdev** [roddhjav/apparmor.d#297]
Hello,

First of all, thank you for providing so many profiles!

I would like to use the one for firefox, but I noticed the presence of the `sys_admin` capability . The question I have is, doesn't this provide root privileges, in which case this could be harmful for potential exploits?

Kind regards

**Comment by roddhjav** [comment]
**To sum up:** thanks to apparmor no.

As commented in the profile, this capability is needed by Firefox (as well as every program that setup user sandbox like chromium) if the kernel is configured such as unprivileged user namespace is blocked. This is an important security feature, therefore the profile must allow it.

If it is true that `sys_admin` has a lot of access, it is not enough by itself. For example:
- A program that want to mount something needs: `sys_admin`, a specific `mount` rule, and write access to the path the mount takes place.
- A program that want to create a ns (like firefox) needs: `sys_admin`, write access to `@{PROC}/@{pid}/{uid,gid}_map` and  `@{PROC}/@{pid}/setgroups`

Also, side note apparmor does not allow anything by itself, it only prevents access to resource not defined in a profile. So you cannot decrease the security with a profile. In other words, Firefox already have access to the `sys_admin` (and `sys_chroot`) through its internal sandbox manager, and the profile can be used in order to ensure the caps are only used to create ns.

**Comment by cdbdev** [comment]
Thank you very much for your thorough and quick response. 

One more question though, if the unpriviledged user namespace is not enabled, it also is not necessary to have the capabilities?

Regards

**Comment by roddhjav** [comment]
Yes, if `sysctl kernel.unprivileged_userns_clone` return `0` (so if it is enabled) this can be removed.

Future version of apparmor will add the `userns,` rule that will allow specific program to create user namespace. This is already supported (if you run ubuntu 24.04): https://github.com/roddhjav/apparmor.d/blob/14fe43714ac646375aa4c4308ca78e95fe157beb/apparmor.d/groups/browsers/firefox#L39
