### ISSUE TITLE
dconf policy?

### ISSUE THREAD

**Issue by nobodysu** [roddhjav/apparmor.d#33]
What do we do with dconf?
Allow write when requested? Allow read? Deny and silence?

**Comment by roddhjav** [comment]
I am asking myself the same question.

In the upstream project (from @morfikov) most of the time dconf was denied. It was fine for his system, it is not on Gnome. For example, without dconf, Firefox just does not start.

So I had to add the dconf abstraction to a few profiles and to add some dconf related rules too. (See [here in Firefox](https://github.com/roddhjav/apparmor.d/blob/501bb66c64500521b998955344536d6dd14596ed/apparmor.d/groups/browsers/firefox#L125) for example)

Up to know this is what I do with dconf when I find it is required. So to sum up allow read when needed, allow write when needed. I don't think AppArmor can do more than this for dconf. I am open to advise on how we should manage it.

**Comment by morfikov** [comment]
Some time ago yes, I had the dconf blocked for all apps in my system, but it's not the case anymore. Many apps rely on dconf to store/read settings, or to request to read system settings. For instance when you save a file, some file dialog pops up. You can have a certain settings for the dialog (i.e. sorting order, etc). All this configuration is usually stored in dconf. If you block dconf in that app, you will have to change the defaults all the time, which can drive you crazy. That's why I allowed dconf in apps that requested it. Gnome require dconf to work properly, so it's not a surprise that apps have issues when dconf is denied. 

In my case the following rules seem to be enough:

```
include <abstractions/dconf>
owner @{run}/user/@{uid}/dconf/ rw,
owner @{run}/user/@{uid}/dconf/user rw,
```

[I once opened this issue in apparmor gitlab](https://gitlab.com/apparmor/apparmor/-/issues/64), but probably people forgot about it.

**Comment by roddhjav** [comment]
Thank for this explanation. Indeed, when needed I think your rules is the best solution.

**Comment by roddhjav** [comment]
Good for me, you can remove the abstraction. Add a section in `CONTRIBUTING.md` would be the best solution.

**Comment by roddhjav** [comment]
We end up with the following solution:
* `<abstractions/dconf>` or,
* `<abstractions/dconf-write>` if write access is required.
