### ISSUE TITLE
Issue: aa-logrpof broken

### ISSUE THREAD

**Issue by Joseph-Edwards** [roddhjav/apparmor.d#463]
After following the installation guide, I ran `aa-log`. There were several `DENIED` messages that I wanted to address, so tried running `aa-logprof` as root. I was met with the following message:

```
Updating AppArmor profiles in /etc/apparmor.d.

ERROR: Invalid or unknown keywords in 'mqueue  r type=posix /
```
Prior to installing `apparmor.d` this worked fine.

I'm happy to provide logs of other output, I'm just not sure would be most useful.

**Comment by roddhjav** [comment]
This is a bug in the apparmor tooling (the tooling does not support the newest apparmor rule such as `mqueue`). It is being fixed on apparmor side. Just use (the more simple) `aa-log` instead of `aa-logprof`

**Comment by harisqazi1** [comment]
Dealing with a similar issue for `aa-genprof` as well, in an attempt to contribute to this project. Using Ubuntu 24.04 on KVM/QEMU. Same error there as well: `ERROR: Invalid or unknown keywords in 'mqueue  r type=posix /`. My question is: For creating new profiles to see what is required for the app to work, genprof was the most efficient way to do this. @roddhjav any recommendations for how to mitigate this issue in the mean time and be able to work on generating profiles (instead of watching syslog | kern.log)? 

I was thinking of using another similar app's profile as a template and then eyeballing what I see in kern.log. Would love to hear your thoughts if there is a better option for this.

**Comment by roddhjav** [comment]
Have a look at `aa-log -r`: https://apparmor.pujol.io/usage/#basic-use
