### ISSUE TITLE
Is there a way to enable apps?

### ISSUE THREAD

**Issue by curiosityseeker** [roddhjav/apparmor.d#471]
I know that _apps_ are ignored in `dists/ignore/main.ignore`. On the other hand, the signal-desktop profile still received an update recently. Is there an easy way to include this group? 

I agree that most ["non-core user applications are out of scope as they should be sandboxed using a dedicated tool (minijail, bubblewrap, toolbox...)"](https://github.com/roddhjav/apparmor.d#concepts). However, the problem with such solutions is broken profile transitions. If you sandbox, e.g., Signal with Firejail and try to open a pdf attachment with your favourite pdf reader this won't work. This is no problem if confining the app with AppArmor. 

Hence, it would be great if we could differentiate between "simple" apps where typically no profile transition is needed (which can consequently be sandboxed) and apps which typically need helper apps (like pdf, image, document viewers). The latter should have an AppArmor profile.

**Comment by roddhjav** [comment]
All profiles in the app group should be moved elsewhere, I keep them here because they are not been tested enough and may require a big update.

> Signal with Firejail and try to open a pdf attachment with your favourite pdf reader this won't work. This is no problem if confining the app with AppArmor.

That's a problem for Firejail. Sandbox manager such as snap/flatpak provide tools to interact with the rest of the desktop in a secure way. All GUI apps need such tool (at minimum to open the documentation program).
